#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 描述/签名
name: Hyperzsb's Ideas
description: 抓住思考的瞬间

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: https://github.hyperzsb.tech

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /blog

#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://github.hyperzsb.tech/blog/assets/images/logo.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://github.hyperzsb.tech/blog/assets/images/favicon.png


# 菜单中的按钮
navigation:
  - name: 首页
    url:
  - name: 归档
    url: archive
  - name: 标签
    url: tags
  - name: 收藏
    url: collections
  - name: 关于
    url: about

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links:
  qq: 1948765057
  email: hyperzsb@outlook.com
  facebook: # https://www.facebook.com/<>
  github: Hyperzsb # https://github.com/<>
  stackoverflow: # http://stackoverflow.com/<>
  twitter: # https://www.twitter.com/<your_twitter_username>
  rss: feed

# 站点页脚的文字
footer-text: Copyright (c) 2020 Hyperzsb
# 站点备案信息
record-text:

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区
disqus: #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 468ab2c347d8544a4cd9
  clientSecret: 7b82ff8ccc241d11915ecd70c8124cfad238bf96
  repo: blog
  owner: Hyperzsb

# 输入Google Analytics web tracking code
google_analytics:

# 显示未来时间的文章
future: false
# 时区配置
timezone: Asia/Shanghai

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v4.0.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  sass_dir: assets/css

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .gitignore
